# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale: "en-US"
site_theme: "default"   # 可选 "default" 或 "air"
# title: "Your Name / Site Title"
# title_separator: "-"
# name: &name "Your Name"
# description: &description "Your Name's academic portfolio"

url: https://YangyangYan96.github.io
baseurl: ""  
repository: "YangyangYan96/YangyangYan96.github.io"

# Author info for sidebar (optional)
author:
  # avatar: "profile.png"
  # name: "Your Sidebar Name"
  # pronouns: "she/her"
  # bio: "Short biography for the sidebar"
  # location: "Earth"
  # employer: "Red Brick University"
  # uri: "https://yourwebsite.com"
  # email: "none@example.org"

# Analytics (optional)
analytics:
  provider: "false"  # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id: ""  # 留空表示不启用

# Reading files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown Processing
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections (optional)
# collections:
#   teaching:
#     output: true
#     permalink: /:collection/:path/
#   publications:
#     output: true
#     permalink: /:collection/:path/
#   portfolio:
#     output: true
#     permalink: /:collection/:path/
#   talks:
#     output: true
#     permalink: /:collection/:path/

# Defaults for pages and posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Output settings
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

